name: Deploy Study App V2 Stack

on:
  push:
    branches: [main, v2-complete-rewrite]
  pull_request:
    branches: [main, v2-complete-rewrite]
  workflow_dispatch:
    inputs:
      stage:
        description: 'Deployment stage (dev/staging/prod)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod
      destroy:
        description: 'Destroy stack instead of deploy'
        required: false
        default: false
        type: boolean

env:
  AWS_REGION: us-east-2
  CDK_VERSION: 2.1024.0
  NODE_VERSION: 20.x

jobs:
  # Job 1: Build and Test
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: |
            cdk-v2/package-lock.json
            lambdas-v2/package-lock.json
            
      - name: Install CDK dependencies
        working-directory: ./cdk-v2
        run: npm ci
        
      - name: Install Lambda dependencies
        working-directory: ./lambdas-v2
        run: npm ci
        
      - name: Build CDK project
        working-directory: ./cdk-v2
        run: npm run build
        
      - name: Build and bundle Lambda functions
        working-directory: ./lambdas-v2
        run: npm run bundle
        
      - name: Run Lambda tests
        working-directory: ./lambdas-v2
        run: npm test -- --passWithNoTests
        
      - name: CDK Synth
        working-directory: ./cdk-v2
        run: |
          export CDK_STAGE=${{ github.event.inputs.stage || 'dev' }}
          export CDK_ACCOUNT=${{ secrets.AWS_ACCOUNT_ID }}
          npm run synth
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-v2
          path: |
            cdk-v2/dist/
            lambdas-v2/bundles/
            cdk-v2/cdk.out/
          retention-days: 7

  # Job 2: Deploy Infrastructure
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/v2-complete-rewrite' && github.event_name != 'pull_request'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts-v2
          
      - name: Install CDK CLI
        run: npm install -g aws-cdk@${{ env.CDK_VERSION }}
        
      - name: Install project dependencies
        working-directory: ./cdk-v2
        run: npm ci
        
      - name: Bootstrap CDK Environment
        run: |
          echo "🚀 Bootstrapping CDK environment..."
          cdk bootstrap aws://${{ secrets.AWS_ACCOUNT_ID }}/${{ env.AWS_REGION }}
        
      - name: Deploy or Destroy Stack
        working-directory: ./cdk-v2
        env:
          CDK_STAGE: ${{ github.event.inputs.stage || 'dev' }}
          CDK_ACCOUNT: ${{ secrets.AWS_ACCOUNT_ID }}
        run: |
          if [ "${{ github.event.inputs.destroy }}" == "true" ]; then
            echo "🗑️ Destroying V2 stack..."
            npm run destroy -- --force
          else
            echo "🚀 Deploying V2 stack..."
            npm run deploy -- --require-approval never
          fi
          
      - name: Output deployment results
        if: github.event.inputs.destroy != 'true'
        working-directory: ./cdk-v2
        env:
          CDK_STAGE: ${{ github.event.inputs.stage || 'dev' }}
          CDK_ACCOUNT: ${{ secrets.AWS_ACCOUNT_ID }}
        run: |
          echo "📋 Stack Outputs:"
          aws cloudformation describe-stacks \
            --stack-name StudyAppStackV2-$CDK_STAGE \
            --query 'Stacks[0].Outputs' \
            --output table
          
          echo ""
          echo "🎉 Deployment completed successfully!"
          
          # Get key URLs for easy access
          API_URL=$(aws cloudformation describe-stacks \
            --stack-name StudyAppStackV2-$CDK_STAGE \
            --query 'Stacks[0].Outputs[?contains(OutputKey, `API`) && contains(OutputKey, `URL`)].OutputValue' \
            --output text | head -1)
          
          CF_URL=$(aws cloudformation describe-stacks \
            --stack-name StudyAppStackV2-$CDK_STAGE \
            --query 'Stacks[0].Outputs[?contains(OutputKey, `CloudFront`) && contains(OutputKey, `URL`)].OutputValue' \
            --output text | head -1)
          
          echo "🌐 API Endpoint: $API_URL"
          echo "☁️ CloudFront URL: $CF_URL" 
          echo "🏥 Health Check: ${API_URL}api/v1/health"